Add API to get visible entries
theia-ide/timeline-chart pull request #117
Opened 2021-03-26 15:17 UTC by MatthewKhouzam

Allow only fetching data that is shown at the moment.

Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>

2021-03-26 15:17 UTC, MatthewKhouzam commented
Not yet ready, showing progress

2021-04-06 18:36 UTC, PatrickTasse requested changes

2021-04-06 18:36 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-chart.ts
> +            console.log("Bounds " + top + " - " + bottom);
remove

2021-04-06 18:36 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-chart.ts
> +                    console.log("Object " + cTop + " - " + cBottom + " / " + top + " - " + bottom);
remove

2021-04-06 18:36 UTC, PatrickTasse commented on timeline-chart/src/layer/time-graph-chart.ts
> +                    if (cTop <= bottom && top <= cBottom) {
It appears that the vertical scrolling is not taken into account. The canvas bounds are unaffected by vertical scrolling, and the row y-position is fixed regardless of scrolling (e.g. it is the position in the full-height virtual scrollable area). Therefore it is always the first few rows of the model being considered visible, even when they are scrolled out of visible range.

2021-09-08 19:49 UTC, closed without merging