Support horizontal panning with middle button or Ctrl+left button
theia-ide/timeline-chart pull request #119
Opened 2021-04-08 19:27 UTC by PatrickTasse

Allow panning with the mouse with middle button drag or Ctrl+left button
drag. Change the cursor to 'grabbing' while panning is ongoing.

Change the cursor to 'grabbing' when only Ctrl is pressed to indicate
that left button can be used to pan.

Restore the cursor to 'default' when panning is ended by releasing the
mouse button that initiated it, or when the conditions to initiate
Ctrl+left button panning are no longer met.

Prevent time selection with any other button than the left button or
when the Ctrl or Alt key is pressed.

Signed-off-by: Patrick Tasse <patrick.tasse@ericsson.com>

2021-04-08 22:38 UTC, bhufmann requested changes
Could you please add a description of panning to https://github.com/theia-ide/timeline-chart/blob/master/doc/documentation.md as well?

2021-04-09 14:00 UTC, bhufmann requested changes
I noticed, using CTRL + left mouse, after mouse up, it's not possible to pan and I have to release the CTRL key and press it again to make it work again. I would expect, while having the CTRL key pressed I can pan multiple times. What do you think?

2021-04-13 12:53 UTC, bhufmann approved these changes
Looks good to me. Thanks.

2021-04-13 18:56 UTC, MatthewKhouzam approved these changes
Works

2021-04-14 14:05 UTC, MatthewKhouzam approved these changes

2021-04-14 14:05 UTC, MatthewKhouzam approved these changes

2021-04-14 14:06 UTC, MatthewKhouzam approved these changes

2021-04-14 15:45 UTC, merged