Fix label overflow
theia-ide/timeline-chart pull request #94
Opened 2021-01-06 07:35 UTC by muddana-satish

Signed-off-by: muddana-satish <satish.muddana@ericsson.com>

2021-01-06 07:38 UTC, muddana-satish commented
I broke this in #69. For some reason, the PIXI BitMap doesn't update the text correctly. Works fine if I create a new object.

2021-01-06 07:50 UTC, muddana-satish commented
Before:

![image](https://user-images.githubusercontent.com/70230232/103743043-89393c00-4fb0-11eb-9532-278fca4f45f2.png)


After:

![image](https://user-images.githubusercontent.com/70230232/103742734-28a9ff00-4fb0-11eb-9c65-aeda189468a8.png)

P.S - This issue is noticeable only when the GPU support is off.

2021-01-06 19:56 UTC, bhufmann requested changes

2021-01-07 08:59 UTC, muddana-satish commented on timeline-chart/src/components/time-graph-row-element.ts
> +        const newTextObj = new PIXI.BitmapText(displayLabel, { fontName: fontName });
Yes. Modified it. Thanks for the suggestion 👍

2021-01-07 18:59 UTC, bhufmann approved these changes
Looks good to me

2021-01-08 19:25 UTC, MatthewKhouzam approved these changes

2021-01-08 19:25 UTC, merged